### ISSUE TITLE
convert-prototype-extensions doesn't work with spread operators

### ISSUE THREAD

**Issue by johnhamelink** [abuiles/ember-watson#19] opened 2015-03-30 18:14 UTC
Hey there :smile: 
I have a model which uses a [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) to dynamically define which attributes should be required for a property. Here's a watered down example which shows the usecase I'm referring to:

    import DS from 'ember-data';

    var attrs = ['lorem', 'ipsum', 'dolor'];
    export default DS.Model.extend({
        filledIn: Ember.computed(...attrs, function(){
            attrs.forEach(function(item){
                console.log(item);
            });
        });
    });

Now, ember-watson will happily convert from property to decorator style, but it breaks when reading through the finished result afterwards:

    Oh Dear! I wasn't able to save the following files:
    app/models/register.js

    A possible cause is having all the source code commented.
    If that's not the problem please fill a report with the hospital directors
    at https://github.com/abuiles/ember-watson/issues.

**Comment by stefanpenner** [comment] 2015-03-30 18:24
dupe of: https://github.com/abuiles/ember-watson/issues/15

**Comment by stefanpenner** [comment] 2015-03-30 18:25
I stole your more succinct issue name.

**Closed by stefanpenner** 2015-03-30 18:24 UTC
